spring.application.name=wallet
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always
server.error.include-exception=true
server.error.include-stacktrace=always
server.address=0.0.0.0
